### ISSUE TITLE
Issues with Library Navigation and Playback Option Menus in 10.8.5

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-tizen#145]
1. I just noticed the playback menu in 10.8.5 has issues that wasn't present in the browser mode. On the Smart TV (RU8000) during a playback, if I were to click on the gear icon, then click on something like the "Aspect Ratio" or "Quality", I could see the list popup momentarily then disappeared. So there's no way to change the options during playback.

2. As for the navigation issues, in the libraries, if you were to place the cursor selection on the thumbnail that's on the far right then trying to click down to select the item below, the selection will go to the "# A B C..." list instead which is by the way looks hidden behind the thumbnails. So you'll need to click left in order to be able to continue select downwards. I don't remember it behaves this way in previous versions.

**Comment by dmitrylyzo** [comment]
> 1\. I just noticed the playback menu in 10.8.5 has issues that wasn't present in the browser mode. On the Smart TV (RU8000) during a playback, if I were to click on the gear icon, then click on something like the "Aspect Ratio" or "Quality", I could see the list popup momentarily then disappeared. So there's no way to change the options during playback.

If you used jf-web `master` branch, this should be fixed by https://github.com/jellyfin/jellyfin-web/pull/3987
10.8.z branch works in the emulator.

> 2\. As for the navigation issues, in the libraries, if you were to place the cursor selection on the thumbnail that's on the far right then trying to click down to select the item below, the selection will go to the "# A B C..." list instead which is by the way looks hidden behind the thumbnails. So you'll need to click left in order to be able to continue select downwards. I don't remember it behaves this way in previous versions.

This can happen if the AlphaPicker overlaps the item view or is too close to it.
Are you using custom CSS theme?

**Comment by Nazar78** [comment]
Hi dmitrylyzo, 

Thanks for replying.

> If you used jf-web `master` branch, this should be fixed by [jellyfin/jellyfin-web#3987](https://github.com/jellyfin/jellyfin-web/pull/3987)
> 10.8.z branch works in the emulator.

I just did a recompile using the master branch, the issue is still there. Only clicking on the "Playback Info" and "Subtitle Offset" works, but not the others.

> This can happen if the AlphaPicker overlaps the item view or is too close to it.
> Are you using custom CSS theme?

No I'm not using any custom CSS theme. Everything is default.

**Comment by dmitrylyzo** [comment]
> I just did a recompile using the master branch, the issue is still there. Only clicking on the "Playback Info" and "Subtitle Offset" works, but not the others.

Still works on my NU7400 (Tizen 4) and in the Tizen 5 emulator. :man_shrugging: 
In `master` this was previously happening because of the use of `resolveOnClick: true` and because of bad browser history handling.
Now there are less hacks.

> No I'm not using any custom CSS theme. Everything is default.

Or do you mean moving to the next incomplete row? _In this case, the AlphaPicker is used because it goes before the item view._
```
x x x x X    A
        v    B
x x x        C
```
https://github.com/jellyfin/jellyfin-web/blob/d1bdbd7a168ca3c842ffff184f2524f4a3c883bc/src/controllers/movies/movies.html#L12-L16
and similar.

Or below the last row?

**Comment by Nazar78** [comment]
> Still works on my NU7400 (Tizen 4) and in the Tizen 5 emulator. 🤷‍♂️
> In `master` this was previously happening because of the use of `resolveOnClick: true` and because of bad browser history handling.
> Now there are less hacks.

I'm not aware of these but it's working perfectly last time. I haven't got the chance to try on the emulator (messed up my dev env) just that it doesn't work on my Tizen 5 RU8000. Do you have any idea what was the cause to have this `resolveOnClick: true` implemented because I believe it was working before it.

> Or below the last row?

With the current selection [X], when I click right on the remote, nothing happens, when I click down, it goes to the last column #. Shouldn't it goes to the row below of the last 2nd column when I click down instead of the going to the #? Strange way to navigate.
> x x x x [X] #
> x x x x x A
> x x x x x B
> x x x x x C

**Comment by dmitrylyzo** [comment]
> Do you have any idea what was the cause to have this `resolveOnClick: true` implemented because I believe it was working before it.

`resolveOnClick: true` should be completely removed, imo - it doesn't work with browser history (https://github.com/jellyfin/jellyfin-web/issues/3978#issuecomment-1265294292).

It is currently almost not used (only single place, iirc).
It was enabled: https://github.com/jellyfin/jellyfin-web/pull/3900
Then, disabled: https://github.com/jellyfin/jellyfin-web/pull/3987

With it:
- Option clicked -> Promise resolved.
- Next menu opened and pushed to the state.
- First dialog is closed, but the next one is also closed.
_Here we could probably filter out, but the state is broken anyway._

FYI, jellyfin-web is slowly moving to React. React router doesn't currently support exiting the app.

> With the current selection [X], when I click right on the remote, nothing happens, when I click down, it goes to the last column #. Shouldn't it goes to the row below of the last 2nd column when I click down instead of the going to the #? Strange way to navigate.

It should navigate down. As I said, the only thing that comes to mind is that AlphaPicker is too close.
Just merged https://github.com/jellyfin/jellyfin-web/pull/4098
Could you try `master` again?

**Comment by Nazar78** [comment]
Hi @dmitrylyzo,

I'm so sorry for the confusion. My mistake as not to check if the app is successfully installed because I was using a batch file. It's been working for a while but now it failed due to certificate issues during install albeit it's the same valid cert I have always been using. I had to update Tizen Studio, delete the old cert then created a new one (Tizen cert no longer works, IIRC was using this, so now I created with Samsung cert). After which I'm stumbled with this new issue instead using the master branch, https://github.com/jellyfin/jellyfin-tizen/issues/144. I had also tested the 10.8.z branch and the mentioned menu and navigation issues doesn't occur.

Sorry again, will close this, I'll now try to debug what's going on with the master branch https://github.com/jellyfin/jellyfin-tizen/issues/144.
