### ISSUE TITLE
Tizen App/Web Failed to construct headers

### ISSUE THREAD

**Issue by hossihub** [jellyfin/jellyfin-tizen#260]
Issue with 10.9 on TV. Failed to construct headers. 

Possible solution to implement ?

https://github.com/remix-run/react-router/pull/11148

**Comment by dmitrylyzo** [comment]
What TV model?
At least the app with 10.9.2 web works in Tizen 5 emulator.

**Comment by tourist1584970446** [comment]
I have the same issue on Tizen 3, 10.8 works fine

**Comment by tacheometry** [comment]
The way to implement my patch is by building my fork of Remix in a separate folder, then [adding a dependency override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to the package.json so that it points to the locally built dependency:
```json
{
  "overrides": {
    "react-router": "file:../patchedReactRouter"
  }
}
```

**Comment by thornbill** [comment]
I suspect we could probably monkey patch the constructor to fix this while waiting on an upstream fix... something like this maybe?

```
var _Headers = window.Headers;
function PatchedHeaders() {
    var args = arguments || {};
    return _Headers.apply(null, args);
}
window.Headers = PatchedHeaders;

**Comment by dmitrylyzo** [comment]
> I suspect we could probably monkey patch the constructor to fix this while waiting on an upstream fix... something like this maybe?

I thought about the same (+maybe try/catch). The question is, does this problem also exist in webOS? If so, we need to do it in web.

**Comment by thornbill** [comment]
Does the same patch work for both? If so let's just get it in web.

**Comment by dmitrylyzo** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/5558

**Comment by ianpaschal** [comment]
This is still occuring for me having just built and deployed the release-10.9.z branch of jellyfin-web.

**Comment by Skyluker4** [comment]
I can also confirm this happening on v10.9.9 jellyfin-web tag. It does not happen on v10.9.8 for me.
