### ISSUE TITLE
Can't change audio language or subtitles

### ISSUE THREAD

**Issue by Kidswiss** [jellyfin/jellyfin-tizen#48]
Hi there

I found an issue today that I'm not able to change the audio track of a movie. It doesn't work when setting it before starting the playback and it doesn't work during the playback. It will just play the first language it finds.

Something similar with the subtitles. It's possible to enable them, but disabling or changing them afterwards doesn't work.

TV: QE55Q6FN
Jellyfin-Tizen version: master
Jellyfin-web version: 10.6.2
Tizen version: 4.0 (not sure though, found that in the specs. No idea where I find the version on the TV itself)

**Comment by SethiPandi** [comment]
I'm also having similar problems, previously it was perfect, but this started after I updated my Jellyfin server and the Jellyfin-Tizen app on my Samsung TV.

1. I'm capable of using the UI to change the audio track, however regardless of what I set it for, it will always use the first audio track and ignore the setting.
2. The subtitles I can update, but it takes around 30 seconds to update and show the new subtitles on the screen. 

#### TV
Name: UE40NU7122
Platform: tv-4.0
Product: https://www.samsung.com/uk/support/model/UE40NU7120KXXU/

#### Jellyfin
Jellyfin-Tizen Version: 4224b92788dae26d2a8c92329ba8c9bdc5cc909a (`master` at time of comment)
Jellyfin-Web Version: 10.6.4 via Docker

**Comment by Kidswiss** [comment]
Can confirm switching subtitles works again with the newest Jellyfin server. Still using 10.6.2 on Tizen.

**Comment by burntoc** [comment]
Interesting that this is sitting open after 9 months.  I can confirm the Fire TVs won't allow changing the audio track.  What's more, despite having English set as my audio and subtitle preference, Jellyfin insists on playing the #1 foreign audio track instead of the #2 English track.  Since I can't change it, I can't use Jellyfin for these movies.  By way of comparison Plex, which I've been trying to put behind me for JF instead for over a year, plays the correct audio track without any intervention beyond my specified global setttings.

**Comment by RomainCZX** [comment]
This problem still exists. Choosing another audio track does not change the track.

**Comment by garret** [comment]
I also have the same issue. Changing audio track does not work both during the viewing and before. Changing subtitle works instead.

**Comment by twsl** [comment]
Any idea whats causing this?

**Comment by dmitrylyzo** [comment]
> Any idea whats causing this?

https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-838282489

**Comment by twsl** [comment]
Hey @dmitrylyzo,
is there anything I can do to support you? I have some experience with web dev but never worked with tizen

**Comment by lexwolf** [comment]
Hi all, any news on the topic? Today I reinstalled the app, hoping the problem was solved, but it's still there. It's kinda sad having to use a Chromecast to be able to select the language :(

**Comment by LucasMZReal** [comment]
I have this issue on WebOS weirdly; and only seemingly for HDR content.

**Comment by Lucipo** [comment]
Issue persists for me on Samsung q75 series TV... Its been five years I mean surely there's a fix?

**Comment by marshalleq** [comment]
Also broken on iPad os.
